/**
 * generated by Xtext 2.12.0
 */
package org.xtext.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.FMRuntimeModule;
import org.xtext.FMStandaloneSetup;
import org.xtext.ide.FMIdeModule;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class FMIdeSetup extends FMStandaloneSetup {
  @Override
  public Injector createInjector() {
    FMRuntimeModule _fMRuntimeModule = new FMRuntimeModule();
    FMIdeModule _fMIdeModule = new FMIdeModule();
    return Guice.createInjector(Modules2.mixin(_fMRuntimeModule, _fMIdeModule));
  }
}
