/**
 * generated by Xtext 2.12.0
 */
package org.xtext.ide;

import org.xtext.ide.AbstractFMIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class FMIdeModule extends AbstractFMIdeModule {
}
