/**
 * generated by Xtext 2.12.0
 */
package org.xtext.fM;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Constraints</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.fM.Constraints#getRules <em>Rules</em>}</li>
 * </ul>
 *
 * @see org.xtext.fM.FMPackage#getConstraints()
 * @model
 * @generated
 */
public interface Constraints extends EObject
{
  /**
   * Returns the value of the '<em><b>Rules</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.fM.Rule}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Rules</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Rules</em>' containment reference list.
   * @see org.xtext.fM.FMPackage#getConstraints_Rules()
   * @model containment="true"
   * @generated
   */
  EList<Rule> getRules();

} // Constraints
