/**
 * generated by Xtext 2.12.0
 */
package org.xtext.fM;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Feature Model</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.fM.FeatureModel#getDiagram <em>Diagram</em>}</li>
 *   <li>{@link org.xtext.fM.FeatureModel#getConstraints <em>Constraints</em>}</li>
 * </ul>
 *
 * @see org.xtext.fM.FMPackage#getFeatureModel()
 * @model
 * @generated
 */
public interface FeatureModel extends EObject
{
  /**
   * Returns the value of the '<em><b>Diagram</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Diagram</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Diagram</em>' containment reference.
   * @see #setDiagram(FeatureDiagram)
   * @see org.xtext.fM.FMPackage#getFeatureModel_Diagram()
   * @model containment="true"
   * @generated
   */
  FeatureDiagram getDiagram();

  /**
   * Sets the value of the '{@link org.xtext.fM.FeatureModel#getDiagram <em>Diagram</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Diagram</em>' containment reference.
   * @see #getDiagram()
   * @generated
   */
  void setDiagram(FeatureDiagram value);

  /**
   * Returns the value of the '<em><b>Constraints</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Constraints</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Constraints</em>' containment reference.
   * @see #setConstraints(Constraints)
   * @see org.xtext.fM.FMPackage#getFeatureModel_Constraints()
   * @model containment="true"
   * @generated
   */
  Constraints getConstraints();

  /**
   * Sets the value of the '{@link org.xtext.fM.FeatureModel#getConstraints <em>Constraints</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Constraints</em>' containment reference.
   * @see #getConstraints()
   * @generated
   */
  void setConstraints(Constraints value);

} // FeatureModel
