/**
 * generated by Xtext 2.12.0
 */
package org.xtext.fM;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.fM.FMFactory
 * @model kind="package"
 * @generated
 */
public interface FMPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "fM";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/FM";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "fM";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  FMPackage eINSTANCE = org.xtext.fM.impl.FMPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.fM.impl.FeatureModelImpl <em>Feature Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.fM.impl.FeatureModelImpl
   * @see org.xtext.fM.impl.FMPackageImpl#getFeatureModel()
   * @generated
   */
  int FEATURE_MODEL = 0;

  /**
   * The feature id for the '<em><b>Diagram</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FEATURE_MODEL__DIAGRAM = 0;

  /**
   * The feature id for the '<em><b>Constraints</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FEATURE_MODEL__CONSTRAINTS = 1;

  /**
   * The number of structural features of the '<em>Feature Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FEATURE_MODEL_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.fM.impl.FeatureDiagramImpl <em>Feature Diagram</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.fM.impl.FeatureDiagramImpl
   * @see org.xtext.fM.impl.FMPackageImpl#getFeatureDiagram()
   * @generated
   */
  int FEATURE_DIAGRAM = 1;

  /**
   * The feature id for the '<em><b>Root</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FEATURE_DIAGRAM__ROOT = 0;

  /**
   * The number of structural features of the '<em>Feature Diagram</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FEATURE_DIAGRAM_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.fM.impl.ChildImpl <em>Child</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.fM.impl.ChildImpl
   * @see org.xtext.fM.impl.FMPackageImpl#getChild()
   * @generated
   */
  int CHILD = 2;

  /**
   * The feature id for the '<em><b>Mandatory</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHILD__MANDATORY = 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHILD__NAME = 1;

  /**
   * The number of structural features of the '<em>Child</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHILD_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.fM.impl.LeafImpl <em>Leaf</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.fM.impl.LeafImpl
   * @see org.xtext.fM.impl.FMPackageImpl#getLeaf()
   * @generated
   */
  int LEAF = 3;

  /**
   * The feature id for the '<em><b>Mandatory</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LEAF__MANDATORY = CHILD__MANDATORY;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LEAF__NAME = CHILD__NAME;

  /**
   * The number of structural features of the '<em>Leaf</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LEAF_FEATURE_COUNT = CHILD_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.xtext.fM.impl.NodeImpl <em>Node</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.fM.impl.NodeImpl
   * @see org.xtext.fM.impl.FMPackageImpl#getNode()
   * @generated
   */
  int NODE = 4;

  /**
   * The feature id for the '<em><b>Mandatory</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NODE__MANDATORY = CHILD__MANDATORY;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NODE__NAME = CHILD__NAME;

  /**
   * The feature id for the '<em><b>Open relation</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NODE__OPEN_RELATION = CHILD_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Children</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NODE__CHILDREN = CHILD_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Close relation</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NODE__CLOSE_RELATION = CHILD_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Node</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NODE_FEATURE_COUNT = CHILD_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link org.xtext.fM.impl.ConstraintsImpl <em>Constraints</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.fM.impl.ConstraintsImpl
   * @see org.xtext.fM.impl.FMPackageImpl#getConstraints()
   * @generated
   */
  int CONSTRAINTS = 5;

  /**
   * The feature id for the '<em><b>Rules</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONSTRAINTS__RULES = 0;

  /**
   * The number of structural features of the '<em>Constraints</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONSTRAINTS_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.fM.impl.RuleImpl <em>Rule</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.fM.impl.RuleImpl
   * @see org.xtext.fM.impl.FMPackageImpl#getRule()
   * @generated
   */
  int RULE = 6;

  /**
   * The feature id for the '<em><b>Elements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RULE__ELEMENTS = 0;

  /**
   * The number of structural features of the '<em>Rule</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RULE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.fM.impl.FormulaImpl <em>Formula</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.fM.impl.FormulaImpl
   * @see org.xtext.fM.impl.FMPackageImpl#getFormula()
   * @generated
   */
  int FORMULA = 8;

  /**
   * The number of structural features of the '<em>Formula</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FORMULA_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.xtext.fM.impl.RuleElementImpl <em>Rule Element</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.fM.impl.RuleElementImpl
   * @see org.xtext.fM.impl.FMPackageImpl#getRuleElement()
   * @generated
   */
  int RULE_ELEMENT = 7;

  /**
   * The feature id for the '<em><b>Open operator</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RULE_ELEMENT__OPEN_OPERATOR = FORMULA_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Left side</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RULE_ELEMENT__LEFT_SIDE = FORMULA_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Right side</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RULE_ELEMENT__RIGHT_SIDE = FORMULA_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Close operator</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RULE_ELEMENT__CLOSE_OPERATOR = FORMULA_FEATURE_COUNT + 3;

  /**
   * The number of structural features of the '<em>Rule Element</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RULE_ELEMENT_FEATURE_COUNT = FORMULA_FEATURE_COUNT + 4;

  /**
   * The meta object id for the '{@link org.xtext.fM.impl.VarImpl <em>Var</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.fM.impl.VarImpl
   * @see org.xtext.fM.impl.FMPackageImpl#getVar()
   * @generated
   */
  int VAR = 9;

  /**
   * The feature id for the '<em><b>Not</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VAR__NOT = FORMULA_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VAR__NAME = FORMULA_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Var</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VAR_FEATURE_COUNT = FORMULA_FEATURE_COUNT + 2;


  /**
   * Returns the meta object for class '{@link org.xtext.fM.FeatureModel <em>Feature Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Feature Model</em>'.
   * @see org.xtext.fM.FeatureModel
   * @generated
   */
  EClass getFeatureModel();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.fM.FeatureModel#getDiagram <em>Diagram</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Diagram</em>'.
   * @see org.xtext.fM.FeatureModel#getDiagram()
   * @see #getFeatureModel()
   * @generated
   */
  EReference getFeatureModel_Diagram();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.fM.FeatureModel#getConstraints <em>Constraints</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Constraints</em>'.
   * @see org.xtext.fM.FeatureModel#getConstraints()
   * @see #getFeatureModel()
   * @generated
   */
  EReference getFeatureModel_Constraints();

  /**
   * Returns the meta object for class '{@link org.xtext.fM.FeatureDiagram <em>Feature Diagram</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Feature Diagram</em>'.
   * @see org.xtext.fM.FeatureDiagram
   * @generated
   */
  EClass getFeatureDiagram();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.fM.FeatureDiagram#getRoot <em>Root</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Root</em>'.
   * @see org.xtext.fM.FeatureDiagram#getRoot()
   * @see #getFeatureDiagram()
   * @generated
   */
  EReference getFeatureDiagram_Root();

  /**
   * Returns the meta object for class '{@link org.xtext.fM.Child <em>Child</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Child</em>'.
   * @see org.xtext.fM.Child
   * @generated
   */
  EClass getChild();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.fM.Child#isMandatory <em>Mandatory</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Mandatory</em>'.
   * @see org.xtext.fM.Child#isMandatory()
   * @see #getChild()
   * @generated
   */
  EAttribute getChild_Mandatory();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.fM.Child#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.fM.Child#getName()
   * @see #getChild()
   * @generated
   */
  EAttribute getChild_Name();

  /**
   * Returns the meta object for class '{@link org.xtext.fM.Leaf <em>Leaf</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Leaf</em>'.
   * @see org.xtext.fM.Leaf
   * @generated
   */
  EClass getLeaf();

  /**
   * Returns the meta object for class '{@link org.xtext.fM.Node <em>Node</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Node</em>'.
   * @see org.xtext.fM.Node
   * @generated
   */
  EClass getNode();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.fM.Node#getOpen_relation <em>Open relation</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Open relation</em>'.
   * @see org.xtext.fM.Node#getOpen_relation()
   * @see #getNode()
   * @generated
   */
  EAttribute getNode_Open_relation();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.fM.Node#getChildren <em>Children</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Children</em>'.
   * @see org.xtext.fM.Node#getChildren()
   * @see #getNode()
   * @generated
   */
  EReference getNode_Children();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.fM.Node#getClose_relation <em>Close relation</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Close relation</em>'.
   * @see org.xtext.fM.Node#getClose_relation()
   * @see #getNode()
   * @generated
   */
  EAttribute getNode_Close_relation();

  /**
   * Returns the meta object for class '{@link org.xtext.fM.Constraints <em>Constraints</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Constraints</em>'.
   * @see org.xtext.fM.Constraints
   * @generated
   */
  EClass getConstraints();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.fM.Constraints#getRules <em>Rules</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Rules</em>'.
   * @see org.xtext.fM.Constraints#getRules()
   * @see #getConstraints()
   * @generated
   */
  EReference getConstraints_Rules();

  /**
   * Returns the meta object for class '{@link org.xtext.fM.Rule <em>Rule</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Rule</em>'.
   * @see org.xtext.fM.Rule
   * @generated
   */
  EClass getRule();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.fM.Rule#getElements <em>Elements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Elements</em>'.
   * @see org.xtext.fM.Rule#getElements()
   * @see #getRule()
   * @generated
   */
  EReference getRule_Elements();

  /**
   * Returns the meta object for class '{@link org.xtext.fM.RuleElement <em>Rule Element</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Rule Element</em>'.
   * @see org.xtext.fM.RuleElement
   * @generated
   */
  EClass getRuleElement();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.fM.RuleElement#getOpen_operator <em>Open operator</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Open operator</em>'.
   * @see org.xtext.fM.RuleElement#getOpen_operator()
   * @see #getRuleElement()
   * @generated
   */
  EAttribute getRuleElement_Open_operator();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.fM.RuleElement#getLeft_side <em>Left side</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left side</em>'.
   * @see org.xtext.fM.RuleElement#getLeft_side()
   * @see #getRuleElement()
   * @generated
   */
  EReference getRuleElement_Left_side();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.fM.RuleElement#getRight_side <em>Right side</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right side</em>'.
   * @see org.xtext.fM.RuleElement#getRight_side()
   * @see #getRuleElement()
   * @generated
   */
  EReference getRuleElement_Right_side();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.fM.RuleElement#getClose_operator <em>Close operator</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Close operator</em>'.
   * @see org.xtext.fM.RuleElement#getClose_operator()
   * @see #getRuleElement()
   * @generated
   */
  EAttribute getRuleElement_Close_operator();

  /**
   * Returns the meta object for class '{@link org.xtext.fM.Formula <em>Formula</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Formula</em>'.
   * @see org.xtext.fM.Formula
   * @generated
   */
  EClass getFormula();

  /**
   * Returns the meta object for class '{@link org.xtext.fM.Var <em>Var</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Var</em>'.
   * @see org.xtext.fM.Var
   * @generated
   */
  EClass getVar();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.fM.Var#isNot <em>Not</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Not</em>'.
   * @see org.xtext.fM.Var#isNot()
   * @see #getVar()
   * @generated
   */
  EAttribute getVar_Not();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.fM.Var#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.fM.Var#getName()
   * @see #getVar()
   * @generated
   */
  EAttribute getVar_Name();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  FMFactory getFMFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.fM.impl.FeatureModelImpl <em>Feature Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.fM.impl.FeatureModelImpl
     * @see org.xtext.fM.impl.FMPackageImpl#getFeatureModel()
     * @generated
     */
    EClass FEATURE_MODEL = eINSTANCE.getFeatureModel();

    /**
     * The meta object literal for the '<em><b>Diagram</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FEATURE_MODEL__DIAGRAM = eINSTANCE.getFeatureModel_Diagram();

    /**
     * The meta object literal for the '<em><b>Constraints</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FEATURE_MODEL__CONSTRAINTS = eINSTANCE.getFeatureModel_Constraints();

    /**
     * The meta object literal for the '{@link org.xtext.fM.impl.FeatureDiagramImpl <em>Feature Diagram</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.fM.impl.FeatureDiagramImpl
     * @see org.xtext.fM.impl.FMPackageImpl#getFeatureDiagram()
     * @generated
     */
    EClass FEATURE_DIAGRAM = eINSTANCE.getFeatureDiagram();

    /**
     * The meta object literal for the '<em><b>Root</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FEATURE_DIAGRAM__ROOT = eINSTANCE.getFeatureDiagram_Root();

    /**
     * The meta object literal for the '{@link org.xtext.fM.impl.ChildImpl <em>Child</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.fM.impl.ChildImpl
     * @see org.xtext.fM.impl.FMPackageImpl#getChild()
     * @generated
     */
    EClass CHILD = eINSTANCE.getChild();

    /**
     * The meta object literal for the '<em><b>Mandatory</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CHILD__MANDATORY = eINSTANCE.getChild_Mandatory();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CHILD__NAME = eINSTANCE.getChild_Name();

    /**
     * The meta object literal for the '{@link org.xtext.fM.impl.LeafImpl <em>Leaf</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.fM.impl.LeafImpl
     * @see org.xtext.fM.impl.FMPackageImpl#getLeaf()
     * @generated
     */
    EClass LEAF = eINSTANCE.getLeaf();

    /**
     * The meta object literal for the '{@link org.xtext.fM.impl.NodeImpl <em>Node</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.fM.impl.NodeImpl
     * @see org.xtext.fM.impl.FMPackageImpl#getNode()
     * @generated
     */
    EClass NODE = eINSTANCE.getNode();

    /**
     * The meta object literal for the '<em><b>Open relation</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute NODE__OPEN_RELATION = eINSTANCE.getNode_Open_relation();

    /**
     * The meta object literal for the '<em><b>Children</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference NODE__CHILDREN = eINSTANCE.getNode_Children();

    /**
     * The meta object literal for the '<em><b>Close relation</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute NODE__CLOSE_RELATION = eINSTANCE.getNode_Close_relation();

    /**
     * The meta object literal for the '{@link org.xtext.fM.impl.ConstraintsImpl <em>Constraints</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.fM.impl.ConstraintsImpl
     * @see org.xtext.fM.impl.FMPackageImpl#getConstraints()
     * @generated
     */
    EClass CONSTRAINTS = eINSTANCE.getConstraints();

    /**
     * The meta object literal for the '<em><b>Rules</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONSTRAINTS__RULES = eINSTANCE.getConstraints_Rules();

    /**
     * The meta object literal for the '{@link org.xtext.fM.impl.RuleImpl <em>Rule</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.fM.impl.RuleImpl
     * @see org.xtext.fM.impl.FMPackageImpl#getRule()
     * @generated
     */
    EClass RULE = eINSTANCE.getRule();

    /**
     * The meta object literal for the '<em><b>Elements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RULE__ELEMENTS = eINSTANCE.getRule_Elements();

    /**
     * The meta object literal for the '{@link org.xtext.fM.impl.RuleElementImpl <em>Rule Element</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.fM.impl.RuleElementImpl
     * @see org.xtext.fM.impl.FMPackageImpl#getRuleElement()
     * @generated
     */
    EClass RULE_ELEMENT = eINSTANCE.getRuleElement();

    /**
     * The meta object literal for the '<em><b>Open operator</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RULE_ELEMENT__OPEN_OPERATOR = eINSTANCE.getRuleElement_Open_operator();

    /**
     * The meta object literal for the '<em><b>Left side</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RULE_ELEMENT__LEFT_SIDE = eINSTANCE.getRuleElement_Left_side();

    /**
     * The meta object literal for the '<em><b>Right side</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RULE_ELEMENT__RIGHT_SIDE = eINSTANCE.getRuleElement_Right_side();

    /**
     * The meta object literal for the '<em><b>Close operator</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RULE_ELEMENT__CLOSE_OPERATOR = eINSTANCE.getRuleElement_Close_operator();

    /**
     * The meta object literal for the '{@link org.xtext.fM.impl.FormulaImpl <em>Formula</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.fM.impl.FormulaImpl
     * @see org.xtext.fM.impl.FMPackageImpl#getFormula()
     * @generated
     */
    EClass FORMULA = eINSTANCE.getFormula();

    /**
     * The meta object literal for the '{@link org.xtext.fM.impl.VarImpl <em>Var</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.fM.impl.VarImpl
     * @see org.xtext.fM.impl.FMPackageImpl#getVar()
     * @generated
     */
    EClass VAR = eINSTANCE.getVar();

    /**
     * The meta object literal for the '<em><b>Not</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VAR__NOT = eINSTANCE.getVar_Not();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VAR__NAME = eINSTANCE.getVar_Name();

  }

} //FMPackage
