/**
 * generated by Xtext 2.12.0
 */
package org.xtext.fM;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Formula</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.fM.FMPackage#getFormula()
 * @model
 * @generated
 */
public interface Formula extends EObject
{
} // Formula
