/**
 * generated by Xtext 2.12.0
 */
package org.xtext.fM;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Leaf</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.fM.FMPackage#getLeaf()
 * @model
 * @generated
 */
public interface Leaf extends Child
{
} // Leaf
