/**
 * generated by Xtext 2.12.0
 */
package org.xtext.fM;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Node</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.fM.Node#getOpen_relation <em>Open relation</em>}</li>
 *   <li>{@link org.xtext.fM.Node#getChildren <em>Children</em>}</li>
 *   <li>{@link org.xtext.fM.Node#getClose_relation <em>Close relation</em>}</li>
 * </ul>
 *
 * @see org.xtext.fM.FMPackage#getNode()
 * @model
 * @generated
 */
public interface Node extends Child
{
  /**
   * Returns the value of the '<em><b>Open relation</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Open relation</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Open relation</em>' attribute.
   * @see #setOpen_relation(String)
   * @see org.xtext.fM.FMPackage#getNode_Open_relation()
   * @model
   * @generated
   */
  String getOpen_relation();

  /**
   * Sets the value of the '{@link org.xtext.fM.Node#getOpen_relation <em>Open relation</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Open relation</em>' attribute.
   * @see #getOpen_relation()
   * @generated
   */
  void setOpen_relation(String value);

  /**
   * Returns the value of the '<em><b>Children</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.fM.Child}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Children</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Children</em>' containment reference list.
   * @see org.xtext.fM.FMPackage#getNode_Children()
   * @model containment="true"
   * @generated
   */
  EList<Child> getChildren();

  /**
   * Returns the value of the '<em><b>Close relation</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Close relation</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Close relation</em>' attribute.
   * @see #setClose_relation(String)
   * @see org.xtext.fM.FMPackage#getNode_Close_relation()
   * @model
   * @generated
   */
  String getClose_relation();

  /**
   * Sets the value of the '{@link org.xtext.fM.Node#getClose_relation <em>Close relation</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Close relation</em>' attribute.
   * @see #getClose_relation()
   * @generated
   */
  void setClose_relation(String value);

} // Node
