/**
 * generated by Xtext 2.12.0
 */
package org.xtext.fM;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Rule Element</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.fM.RuleElement#getOpen_operator <em>Open operator</em>}</li>
 *   <li>{@link org.xtext.fM.RuleElement#getLeft_side <em>Left side</em>}</li>
 *   <li>{@link org.xtext.fM.RuleElement#getRight_side <em>Right side</em>}</li>
 *   <li>{@link org.xtext.fM.RuleElement#getClose_operator <em>Close operator</em>}</li>
 * </ul>
 *
 * @see org.xtext.fM.FMPackage#getRuleElement()
 * @model
 * @generated
 */
public interface RuleElement extends Formula
{
  /**
   * Returns the value of the '<em><b>Open operator</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Open operator</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Open operator</em>' attribute.
   * @see #setOpen_operator(String)
   * @see org.xtext.fM.FMPackage#getRuleElement_Open_operator()
   * @model
   * @generated
   */
  String getOpen_operator();

  /**
   * Sets the value of the '{@link org.xtext.fM.RuleElement#getOpen_operator <em>Open operator</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Open operator</em>' attribute.
   * @see #getOpen_operator()
   * @generated
   */
  void setOpen_operator(String value);

  /**
   * Returns the value of the '<em><b>Left side</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Left side</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Left side</em>' containment reference.
   * @see #setLeft_side(Var)
   * @see org.xtext.fM.FMPackage#getRuleElement_Left_side()
   * @model containment="true"
   * @generated
   */
  Var getLeft_side();

  /**
   * Sets the value of the '{@link org.xtext.fM.RuleElement#getLeft_side <em>Left side</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Left side</em>' containment reference.
   * @see #getLeft_side()
   * @generated
   */
  void setLeft_side(Var value);

  /**
   * Returns the value of the '<em><b>Right side</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Right side</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Right side</em>' containment reference.
   * @see #setRight_side(Var)
   * @see org.xtext.fM.FMPackage#getRuleElement_Right_side()
   * @model containment="true"
   * @generated
   */
  Var getRight_side();

  /**
   * Sets the value of the '{@link org.xtext.fM.RuleElement#getRight_side <em>Right side</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Right side</em>' containment reference.
   * @see #getRight_side()
   * @generated
   */
  void setRight_side(Var value);

  /**
   * Returns the value of the '<em><b>Close operator</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Close operator</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Close operator</em>' attribute.
   * @see #setClose_operator(String)
   * @see org.xtext.fM.FMPackage#getRuleElement_Close_operator()
   * @model
   * @generated
   */
  String getClose_operator();

  /**
   * Sets the value of the '{@link org.xtext.fM.RuleElement#getClose_operator <em>Close operator</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Close operator</em>' attribute.
   * @see #getClose_operator()
   * @generated
   */
  void setClose_operator(String value);

} // RuleElement
