/*
 * generated by Xtext 2.12.0
 */
package org.xtext.ui.tests;

import com.google.inject.Injector;
import dslProject.ui.internal.DslProjectActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class FMUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return DslProjectActivator.getInstance().getInjector("org.xtext.FM");
	}

}
