/*
 * generated by Xtext 2.12.0
 */
package org.xtext.web;

import org.eclipse.xtext.web.server.DefaultWebModule;

/**
 * Manual modifications go to {@link FMWebModule}.
 */
@SuppressWarnings("all")
public abstract class AbstractFMWebModule extends DefaultWebModule {

}
