/**
 * generated by Xtext 2.12.0
 */
package org.xtext.web;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.FMRuntimeModule;
import org.xtext.FMStandaloneSetup;
import org.xtext.ide.FMIdeModule;
import org.xtext.web.FMWebModule;

/**
 * Initialization support for running Xtext languages in web applications.
 */
@SuppressWarnings("all")
public class FMWebSetup extends FMStandaloneSetup {
  @Override
  public Injector createInjector() {
    FMRuntimeModule _fMRuntimeModule = new FMRuntimeModule();
    FMIdeModule _fMIdeModule = new FMIdeModule();
    FMWebModule _fMWebModule = new FMWebModule();
    return Guice.createInjector(Modules2.mixin(_fMRuntimeModule, _fMIdeModule, _fMWebModule));
  }
}
