/**
 * generated by Xtext 2.12.0
 */
package org.xtext.web;

import org.xtext.web.AbstractFMWebModule;

/**
 * Use this class to register additional components to be used within the web application.
 */
@SuppressWarnings("all")
public class FMWebModule extends AbstractFMWebModule {
}
