/**
 * generated by Xtext 2.12.0
 */
package org.xtext;

import org.xtext.AbstractFMRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class FMRuntimeModule extends AbstractFMRuntimeModule {
}
