/*
 * generated by Xtext 2.12.0
 */
package org.xtext.ide

import com.google.inject.Guice
import org.eclipse.xtext.util.Modules2
import org.xtext.FMRuntimeModule
import org.xtext.FMStandaloneSetup

/**
 * Initialization support for running Xtext languages as language servers.
 */
class FMIdeSetup extends FMStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new FMRuntimeModule, new FMIdeModule))
	}
	
}
