/*
 * generated by Xtext 2.12.0
 */
package org.xtext.ui;

import com.google.inject.Injector;
import dslProject.ui.internal.DslProjectActivator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class FMExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return DslProjectActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return DslProjectActivator.getInstance().getInjector(DslProjectActivator.ORG_XTEXT_FM);
	}
	
}
