/*
 * generated by Xtext 2.12.0
 */
package org.xtext.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.parser.antlr.internal.InternalFMParser;
import org.xtext.services.FMGrammarAccess;

public class FMParser extends AbstractAntlrParser {

	@Inject
	private FMGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalFMParser createParser(XtextTokenStream stream) {
		return new InternalFMParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "FeatureModel";
	}

	public FMGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(FMGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
